@PaymentService.API_HostAddress = https://localhost:7027/api

POST {{PaymentService.API_HostAddress}}/payment/CreateOrder
Accept: application/json
Content-Type:application/json
{
  "Amount":1000,
  "Currency":"INR",
  "Receipt":"hi"
}
###
