@AuthService.API_HostAddress = https://localhost:7209/api

POST {{AuthService.API_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json
{
  "email":"user@gmail.com",
  "password":"User@12345678"
}
###
POST {{AuthService.API_HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json
{
  "name":"Mohan",
  "email":"mohan@gmail.com",
  "password":"User@12345678",
  "phoneNumber":"9876543210",
  "role":"User"
}