@AuthService.API_HostAddress = http://localhost:5118/api


### Register User
POST {{AuthService.API_HostAddress}}/auth/Register
Accept: application/json
content-Type:application/json
{
  "email":"priya@gmail.com",
  "password":"User@12345678",
  "role":"User",
  "phoneNumber":"User@12345678",
  "name":"Priya"
}

### Login User
POST {{AuthService.API_HostAddress}}/auth/Login
Accept: application/json
content-Type:application/json
{
  "email":"user@gmail.com",
  "password":"User@12345678"
}


###
